// @ts-nocheck
import test from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import { executeTrustedCommit } from "../src/trusted-commit-orchestrator.js";
import { InMemoryAtomicCommitBackend } from "../src/storage-atomic-commit-adapter.js";
import { canonicalDelegationPayload, canonicalRevocationPayload, publicKeyFingerprintSha256 } from "../src/external-trust-root.js";
import { canonicalProvenanceAttestationPayload, canonicalTrustAnchorRegistryPayload } from "../src/trust-anchor-provenance.js";

const NOW = "2026-09-11T08:30:00+09:00";
const PROOF_TYPE = "ED25519-PROVENANCE-V1";
const pair = () => generateKeyPairSync("ed25519");
const pem = (key) => key.export({ type: "spki", format: "pem" }).toString();
const sig = (key, payload) => sign(null, Buffer.from(payload, "utf8"), key).toString("base64");
const subject = (kind,id,version=null,path=null) => ({subjectKind:kind,subjectId:id,subjectVersion:version,subjectPath:path,stateId:"CS-MAIN",stateRevision:12,lineageId:"LINEAGE-MAIN-001"});

function fixture() {
  const current={identity:{stateId:"CS-MAIN",schemaVersion:"0.1",stateRevision:12,effectiveAt:"2026-09-11T08:00:00+09:00",scope:"KIYUSAMA_OS_2",lineageId:"LINEAGE-MAIN-001"},humanDecisionFinal:{decisionId:"HD-1",sourceAuthority:"KIYUSAMA",shortDirective:"execute"},mainLineTask:{taskId:"ML-1",description:"integration"},nextActionSingle:{actionId:"NA-1",description:"execute integration action"},activeRolesAndAuthority:{EVIDENCE_AUTHORITY:"AUTH-EVIDENCE-1",LANE_AUTHORITY:"AUTH-LANE-1",IDENTITY_AUTHORITY:"AUTH-IDENTITY-1"},activeGuards:[],confirmedRefIndex:[{id:"REF-1",status:"VERIFIED",expectedVersion:"v7",path:"evidence/ref-1.json"}],independentLaneHealth:{status:"VERIFIED",evidenceVerdict:"SUFFICIENT",observedAt:"2026-09-11T08:20:00+09:00",evidenceSource:"KIRA-INDEPENDENT"}};
  const rootPair=pair(), rootPem=pem(rootPair.publicKey);
  const root={rootId:"ROOT-1",rootVersion:"1",algorithm:"ED25519",publicKeyPem:rootPem,validFrom:"2026-09-01T00:00:00+09:00",validUntil:null};
  const proofPairs={"AUTH-EVIDENCE-1":pair(),"AUTH-LANE-1":pair(),"AUTH-IDENTITY-1":pair()};
  const delegatedProofKeys=[["PROOF-EVIDENCE","AUTH-EVIDENCE-1"],["PROOF-LANE","AUTH-LANE-1"],["PROOF-IDENTITY","AUTH-IDENTITY-1"]].map(([proofKeyId,authority])=>{const publicKeyPem=pem(proofPairs[authority].publicKey);const k={proofKeyId,rootId:"ROOT-1",rootVersion:"1",issuerAuthorityId:authority,proofType:PROOF_TYPE,algorithm:"ED25519",publicKeyPem,publicKeyFingerprintSha256:publicKeyFingerprintSha256(publicKeyPem),validFrom:"2026-09-01T00:00:00+09:00",validUntil:null,delegationSignatureBase64:""};k.delegationSignatureBase64=sig(rootPair.privateKey,canonicalDelegationPayload(k));return k;});
  const revocation={snapshotId:"REV-40",rootId:"ROOT-1",rootVersion:"1",sequence:40,issuedAt:"2026-09-11T08:00:00+09:00",expiresAt:"2026-09-11T09:00:00+09:00",revokedProofKeyIds:[],signatureBase64:""};revocation.signatureBase64=sig(rootPair.privateKey,canonicalRevocationPayload(revocation));
  const anchors=[{anchorId:"ANCHOR-EVIDENCE",anchorVersion:"1",subjectKind:"EVIDENCE_REF",authorityRole:"EVIDENCE_AUTHORITY",authorityId:"AUTH-EVIDENCE-1",status:"ACTIVE",validFrom:"2026-09-01T00:00:00+09:00",validUntil:null},{anchorId:"ANCHOR-LANE",anchorVersion:"1",subjectKind:"INDEPENDENT_LANE",authorityRole:"LANE_AUTHORITY",authorityId:"AUTH-LANE-1",status:"ACTIVE",validFrom:"2026-09-01T00:00:00+09:00",validUntil:null},{anchorId:"ANCHOR-IDENTITY",anchorVersion:"1",subjectKind:"VERIFIER_IDENTITY",authorityRole:"IDENTITY_AUTHORITY",authorityId:"AUTH-IDENTITY-1",status:"ACTIVE",validFrom:"2026-09-01T00:00:00+09:00",validUntil:null}];
  const registry={registryId:"REGISTRY-1",registryRevision:5,anchors,rootSignatureBase64:""};registry.rootSignatureBase64=sig(rootPair.privateKey,canonicalTrustAnchorRegistryPayload(registry));
  const attestations=[{attestationId:"ATT-EVIDENCE",anchorId:"ANCHOR-EVIDENCE",anchorVersion:"1",issuerAuthorityId:"AUTH-EVIDENCE-1",subject:subject("EVIDENCE_REF","REF-1","v7","evidence/ref-1.json"),issuedAt:"2026-09-11T08:10:00+09:00",expiresAt:"2026-09-11T08:50:00+09:00",proofType:PROOF_TYPE,proofKeyId:"PROOF-EVIDENCE",proofValue:""},{attestationId:"ATT-LANE",anchorId:"ANCHOR-LANE",anchorVersion:"1",issuerAuthorityId:"AUTH-LANE-1",subject:subject("INDEPENDENT_LANE","KIRA-INDEPENDENT"),issuedAt:"2026-09-11T08:10:00+09:00",expiresAt:"2026-09-11T08:50:00+09:00",proofType:PROOF_TYPE,proofKeyId:"PROOF-LANE",proofValue:""},{attestationId:"ATT-IDENTITY",anchorId:"ANCHOR-IDENTITY",anchorVersion:"1",issuerAuthorityId:"AUTH-IDENTITY-1",subject:subject("VERIFIER_IDENTITY","KIRA-INDEPENDENT"),issuedAt:"2026-09-11T08:10:00+09:00",expiresAt:"2026-09-11T08:50:00+09:00",proofType:PROOF_TYPE,proofKeyId:"PROOF-IDENTITY",proofValue:""}];
  for(const a of attestations)a.proofValue=sig(proofPairs[a.issuerAuthorityId].privateKey,canonicalProvenanceAttestationPayload(a));
  const handoff={handoffId:"HANDOFF-1",traceId:"TRACE-1",actionId:"NA-1",sourceStateId:"CS-MAIN",sourceStateRevision:12,capabilityId:"CAP-1",implementationId:"IMPL-1",issuedAt:"2026-09-11T08:20:00+09:00",expiresAt:"2026-09-11T08:50:00+09:00",evidenceRefs:[{id:"REF-1",expectedVersion:"v7",path:"evidence/ref-1.json"}],resultEvidencePolicy:{requiredRefs:[{id:"REF-1",expectedVersion:"v7",path:"evidence/ref-1.json"}],verifierId:"KIRA-INDEPENDENT",evidenceSource:"KIRA-INDEPENDENT"}};
  const result={resultId:"RESULT-1",handoffId:"HANDOFF-1",traceId:"TRACE-1",actionId:"NA-1",sourceStateId:"CS-MAIN",sourceStateRevision:12,capabilityId:"CAP-1",implementationId:"IMPL-1",executorId:"EXECUTOR-1",verifierId:"KIRA-INDEPENDENT",outcome:"SUCCEEDED",providerExecutionId:"PROVIDER-1",observedAt:"2026-09-11T08:25:00+09:00",evidenceRefIds:["REF-1"],verification:"VERIFIED"};
  const candidate={...current,identity:{...current.identity,stateRevision:13,effectiveAt:"2026-09-11T08:31:00+09:00"},writeBack:{parent:{parentStateId:"CS-MAIN",parentRevision:12},source:{sourceResultId:"RESULT-1",sourceHandoffId:"HANDOFF-1"}}};
  const pipeline={snapshot:current,memoryRecord:{id:"MEM-CURRENT-12",memoryClass:"CURRENT",payload:current},actionEvidenceRequirement:{actionId:"NA-1",requiredRefs:[{id:"REF-1",expectedVersion:"v7",path:"evidence/ref-1.json"}],requireIndependentLane:true},requiredCapabilityId:"CAP-1",capabilitySlot:{slotId:"SLOT-1",capabilityId:"CAP-1",status:"BOUND",binding:{capabilityId:"CAP-1",implementationId:"IMPL-1",source:"NATIVE",version:"1",verified:true}},handoff,result,provenance:{registry,attestations,externalTrust:{root,expectedRootFingerprintSha256:publicKeyFingerprintSha256(rootPem),delegatedProofKeys,revocationSnapshot:revocation,minRevocationSequence:40,now:NOW},now:NOW},writeBackRequest:{writeBackId:"WB-1",parent:{parentStateId:"CS-MAIN",parentRevision:12},source:{sourceResultId:"RESULT-1",sourceHandoffId:"HANDOFF-1"},consumption:{resultConsumptionKey:"RESULT-1",handoffConsumptionKey:"HANDOFF-1"},cas:{expectedCurrentStateId:"CS-MAIN",expectedCurrentRevision:12},candidate},consumedResultIds:new Set(),consumedHandoffIds:new Set(),now:NOW};
  return { pipeline, backend:new InMemoryAtomicCommitBackend({current}) };
}

test("normal verified path commits exactly once", async()=>{const f=fixture();const d=await executeTrustedCommit(f);assert.equal(d.status,"COMMITTED");assert.equal(d.commitSequence,1);assert.equal(f.backend.snapshot().current.identity.stateRevision,13);});
test("forged provenance never invokes backend", async()=>{const f=fixture();let calls=0;const backend={compareConsumeAndSwap(){calls++;throw new Error("must not call");}};f.pipeline.provenance.attestations[0].proofValue="FORGED";const d=await executeTrustedCommit({pipeline:f.pipeline,backend});assert.equal(d.status,"HOLD");assert.equal(d.stage,"TRUST_PIPELINE");assert.equal(calls,0);});
test("unauthorized candidate mutation never invokes backend", async()=>{const f=fixture();let calls=0;const backend={compareConsumeAndSwap(){calls++;throw new Error("must not call");}};f.pipeline.writeBackRequest.candidate.nextActionSingle={actionId:"ATTACK",description:"hijack"};const d=await executeTrustedCommit({pipeline:f.pipeline,backend});assert.equal(d.status,"HOLD");assert.equal(calls,0);});
test("backend revision conflict is fail closed", async()=>{const f=fixture();const first=await executeTrustedCommit(f);assert.equal(first.status,"COMMITTED");const second=await executeTrustedCommit(f);assert.deepEqual(second,{status:"HOLD",stage:"ATOMIC_COMMIT",reason:"REVISION_CONFLICT"});});
test("backend throw is fail closed", async()=>{const f=fixture();const backend={compareConsumeAndSwap(){throw new Error("boom");}};assert.deepEqual(await executeTrustedCommit({pipeline:f.pipeline,backend}),{status:"HOLD",stage:"ATOMIC_COMMIT",reason:"BACKEND_FAILURE"});});
test("result replay is blocked at pipeline before backend", async()=>{const f=fixture();let calls=0;const backend={compareConsumeAndSwap(){calls++;throw new Error("must not call");}};f.pipeline.consumedResultIds.add("RESULT-1");const d=await executeTrustedCommit({pipeline:f.pipeline,backend});assert.equal(d.status,"HOLD");assert.equal(d.pipelineStage,"WRITE_BACK");assert.equal(calls,0);});
