export const COMMERCE_CAPABILITIES = ['DRAFT_TITLE','DRAFT_DESCRIPTION','PRICE_ANALYSIS','IMAGE_ORGANIZE','LIST_ITEM','BUY_ITEM','MESSAGE','TRANSACTION'] as const;
export type CommerceCapability = (typeof COMMERCE_CAPABILITIES)[number];
export const COMMERCE_ROUTE_STATES = ['VERIFIED','UNKNOWN','UNAVAILABLE'] as const;
export type CommerceRouteState = (typeof COMMERCE_ROUTE_STATES)[number];
export interface CommerceCapabilityState { capability: CommerceCapability; route_state: CommerceRouteState; human_confirmation_required: boolean; }
export interface CommerceAsset { schema_version:'kiyusama-commerce-asset/2.0-draft1'; asset_id:string; service:string; device_presence:'VERIFIED'|'UNKNOWN'; capabilities:CommerceCapabilityState[]; guard_refs:string[]; evidence_refs:string[]; observed_at:string; }
export interface CommerceValidation { ok:boolean; issues:string[] }
const s=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0;
const o=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const t=(v:unknown)=>s(v)&&!Number.isNaN(Date.parse(v));
const actionCaps=new Set<CommerceCapability>(['LIST_ITEM','BUY_ITEM','MESSAGE','TRANSACTION']);
export function validateCommerceAsset(x:unknown):CommerceValidation { const issues:string[]=[]; if(!o(x)) return {ok:false,issues:['$ must be object']}; if(x.schema_version!=='kiyusama-commerce-asset/2.0-draft1') issues.push('schema_version invalid'); if(!s(x.asset_id)) issues.push('asset_id required'); if(!s(x.service)) issues.push('service required'); if(x.device_presence!=='VERIFIED'&&x.device_presence!=='UNKNOWN') issues.push('device_presence invalid'); if(!Array.isArray(x.capabilities)||x.capabilities.length===0) issues.push('capabilities required'); else for(const c of x.capabilities){ if(!o(c)||!COMMERCE_CAPABILITIES.includes(c.capability as CommerceCapability)||!COMMERCE_ROUTE_STATES.includes(c.route_state as CommerceRouteState)||typeof c.human_confirmation_required!=='boolean'){issues.push('capability entry invalid');continue;} if(actionCaps.has(c.capability as CommerceCapability)&&c.human_confirmation_required!==true) issues.push(`${c.capability} requires human confirmation`); } if(!Array.isArray(x.guard_refs)||x.guard_refs.some(v=>!s(v))) issues.push('guard_refs invalid'); if(!Array.isArray(x.evidence_refs)||x.evidence_refs.some(v=>!s(v))) issues.push('evidence_refs invalid'); if(x.device_presence==='VERIFIED'&&(!Array.isArray(x.evidence_refs)||x.evidence_refs.length===0)) issues.push('VERIFIED device presence requires evidence'); if(!t(x.observed_at)) issues.push('observed_at invalid'); return {ok:issues.length===0,issues}; }
