export const RESULT_STATUSES = ['SUCCESS', 'FAILED', 'TIMEOUT', 'QUOTA_EXCEEDED'] as const;
export type ResultStatus = (typeof RESULT_STATUSES)[number];
export const OUTPUT_FORMATS = ['text', 'json', 'markdown'] as const;
export type OutputFormat = (typeof OUTPUT_FORMATS)[number];

export interface ProviderExecutionRef { session_id?: string; deployment_run_id?: string; run_id?: string; [key: string]: unknown }
export interface UniversalResultContainer { schema_version:'device-result/0.1'; device_event_id:string; delivery_event_id:string; hop:number; provider:string; provider_execution:ProviderExecutionRef; status:ResultStatus; output:{format:OutputFormat;text:string;structured:Record<string,unknown>|null}; metrics:{duration_ms:number;turns_count?:number}; error:{code:string;message:string}|null; completed_at:string }
export interface ValidationIssue { path:string; message:string }
export type ValidationResult<T>={ok:true;value:T}|{ok:false;issues:ValidationIssue[]};
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const isNonEmptyString=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0;
const isFiniteNonNegativeNumber=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const isPositiveInteger=(v:unknown):v is number=>typeof v==='number'&&Number.isInteger(v)&&v>=1;
const isRfc3339=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&!Number.isNaN(Date.parse(v));
export function validateUniversalResultContainer(input:unknown):ValidationResult<UniversalResultContainer>{const issues:ValidationIssue[]=[];if(!isRecord(input))return{ok:false,issues:[{path:'$',message:'must be an object'}]};if(input.schema_version!=='device-result/0.1')issues.push({path:'schema_version',message:'must equal device-result/0.1'});if(!isNonEmptyString(input.device_event_id))issues.push({path:'device_event_id',message:'must be a non-empty string'});if(!isNonEmptyString(input.delivery_event_id))issues.push({path:'delivery_event_id',message:'must be a non-empty string'});if(!isPositiveInteger(input.hop))issues.push({path:'hop',message:'must be a positive integer'});if(!isNonEmptyString(input.provider))issues.push({path:'provider',message:'must be a non-empty string'});if(!isRecord(input.provider_execution))issues.push({path:'provider_execution',message:'must be an object'});if(!RESULT_STATUSES.includes(input.status as ResultStatus))issues.push({path:'status',message:'invalid'});if(!isRecord(input.output))issues.push({path:'output',message:'must be an object'});else{if(!OUTPUT_FORMATS.includes(input.output.format as OutputFormat))issues.push({path:'output.format',message:'invalid'});if(typeof input.output.text!=='string')issues.push({path:'output.text',message:'must be a string'});if(!(input.output.structured===null||isRecord(input.output.structured)))issues.push({path:'output.structured',message:'must be object or null'})}if(!isRecord(input.metrics))issues.push({path:'metrics',message:'must be object'});else{if(!isFiniteNonNegativeNumber(input.metrics.duration_ms))issues.push({path:'metrics.duration_ms',message:'invalid'});if(input.metrics.turns_count!==undefined&&!(typeof input.metrics.turns_count==='number'&&Number.isInteger(input.metrics.turns_count)&&input.metrics.turns_count>=0))issues.push({path:'metrics.turns_count',message:'invalid'})}if(input.error!==null){if(!isRecord(input.error))issues.push({path:'error',message:'must be object or null'});else{if(!isNonEmptyString(input.error.code))issues.push({path:'error.code',message:'required'});if(!isNonEmptyString(input.error.message))issues.push({path:'error.message',message:'required'})}}if(!isRfc3339(input.completed_at))issues.push({path:'completed_at',message:'invalid'});if(input.status==='SUCCESS'&&input.error!==null)issues.push({path:'error',message:'must be null when SUCCESS'});if(RESULT_STATUSES.includes(input.status as ResultStatus)&&input.status!=='SUCCESS'&&input.error===null)issues.push({path:'error',message:'required when non-SUCCESS'});return issues.length?{ok:false,issues}:{ok:true,value:input as unknown as UniversalResultContainer}}
export function isValidUniversalResultContainer(input:unknown):input is UniversalResultContainer{return validateUniversalResultContainer(input).ok}

/** Legacy seven-stage vocabulary: compatibility/evidence only, never final OS 2.0 topology. */
export const LEGACY_TONTON_STAGES=['WATCH','WAKE','ROUTE','DELIVER','ACK','VERIFY','RECORD'] as const; export type LegacyTontonStage=(typeof LEGACY_TONTON_STAGES)[number];
export const LEGACY_TONTON_STAGE_STATUSES=['PENDING','STARTED','SUCCESS','FAILED','SKIPPED_COMPAT','BLOCKED'] as const; export type LegacyTontonStageStatus=(typeof LEGACY_TONTON_STAGE_STATUSES)[number];
export interface LegacyTontonStageRecord{schema_version:'tonton-stage/legacy-7stage-v1';flow_id:string;event_id:string;stage:LegacyTontonStage;actor:string;target:string;previous_stage:LegacyTontonStage|null;status:LegacyTontonStageStatus;evidence_ref:string|null;created_at:string;next_stage:LegacyTontonStage|null;failure_reason:string|null;legacy_ref?:string;metadata?:Record<string,unknown>}
const legacyStageIndex=(s:LegacyTontonStage)=>LEGACY_TONTON_STAGES.indexOf(s);
export function validateLegacyTontonStageRecord(input:unknown):ValidationResult<LegacyTontonStageRecord>{const issues:ValidationIssue[]=[];if(!isRecord(input))return{ok:false,issues:[{path:'$',message:'must be object'}]};if(input.schema_version!=='tonton-stage/legacy-7stage-v1')issues.push({path:'schema_version',message:'invalid'});for(const k of ['flow_id','event_id','actor','target'] as const)if(!isNonEmptyString(input[k]))issues.push({path:k,message:'required'});if(!LEGACY_TONTON_STAGES.includes(input.stage as LegacyTontonStage))issues.push({path:'stage',message:'invalid'});if(!(input.previous_stage===null||LEGACY_TONTON_STAGES.includes(input.previous_stage as LegacyTontonStage)))issues.push({path:'previous_stage',message:'invalid'});if(!LEGACY_TONTON_STAGE_STATUSES.includes(input.status as LegacyTontonStageStatus))issues.push({path:'status',message:'invalid'});if(!(input.evidence_ref===null||isNonEmptyString(input.evidence_ref)))issues.push({path:'evidence_ref',message:'invalid'});if(!isRfc3339(input.created_at))issues.push({path:'created_at',message:'invalid'});if(!(input.next_stage===null||LEGACY_TONTON_STAGES.includes(input.next_stage as LegacyTontonStage)))issues.push({path:'next_stage',message:'invalid'});if(!(input.failure_reason===null||isNonEmptyString(input.failure_reason)))issues.push({path:'failure_reason',message:'invalid'});const stage=LEGACY_TONTON_STAGES.includes(input.stage as LegacyTontonStage)?input.stage as LegacyTontonStage:null;const prev=LEGACY_TONTON_STAGES.includes(input.previous_stage as LegacyTontonStage)?input.previous_stage as LegacyTontonStage:null;const next=LEGACY_TONTON_STAGES.includes(input.next_stage as LegacyTontonStage)?input.next_stage as LegacyTontonStage:null;if(stage==='WATCH'&&input.previous_stage!==null)issues.push({path:'previous_stage',message:'WATCH starts null'});if(stage==='RECORD'&&input.next_stage!==null&&input.next_stage!=='WATCH')issues.push({path:'next_stage',message:'RECORD terminates or WATCH'});if(stage&&prev&&legacyStageIndex(prev)>=legacyStageIndex(stage))issues.push({path:'previous_stage',message:'must precede'});if(stage&&next&&stage!=='RECORD'&&legacyStageIndex(next)<=legacyStageIndex(stage))issues.push({path:'next_stage',message:'must follow'});if(input.status==='FAILED'&&input.failure_reason===null)issues.push({path:'failure_reason',message:'required'});if(input.status==='SUCCESS'&&input.failure_reason!==null)issues.push({path:'failure_reason',message:'must be null'});if((stage==='VERIFY'||stage==='RECORD')&&input.status==='SUCCESS'&&input.evidence_ref===null)issues.push({path:'evidence_ref',message:'required'});return issues.length?{ok:false,issues}:{ok:true,value:input as unknown as LegacyTontonStageRecord}}
export function isValidLegacyTontonStageRecord(input:unknown):input is LegacyTontonStageRecord{return validateLegacyTontonStageRecord(input).ok}

export * from './memory-continuation.js';
export * from './core-interface.js';
export * from './worker-fabric.js';
export * from './counter-lane.js';
