import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";
import {DurableBodyLock,DurableLedger} from "./durable-core.mjs";import {GuardianState} from "./control-core.mjs";
import {assembleFinalSessionAdapter,rejectSeparatedCapabilityAssembly,FinalSessionAdapterError} from "./final-session-adapter.mjs";
function rig(){const d=fs.mkdtempSync(path.join(os.tmpdir(),"gfinal-"));const lock=new DurableBodyLock(path.join(d,"l"));const ledger=new DurableLedger(path.join(d,"j"));lock.acquire({bodyId:"B",ownerId:"O"});ledger.record("B",{state:GuardianState.LOCKED,ownerId:"O",workId:"W",preSendCommitted:true,sendStarted:false,resultCommitted:false});let s=0,r=0;const a=assembleFinalSessionAdapter({bodyId:"B",ownerId:"O",workId:"W",expectedUserTurnId:"u",lock,ledger,rawSend:async()=>{s++},rawResultCommit:async({saved})=>{r++;return saved},observe:()=>1,compose:x=>x,captureReturn:async()=>({causalUserTurnId:"u",assistantTurnId:"a",streamEnded:true,contentStable:true,sameBody:true})});return{a,ledger,get s(){return s},get r(){return r}}}
test("final adapter public surface is observe compose send capture only",()=>{const x=rig();assert.deepEqual(Object.keys(x.a).sort(),["capture","compose","observe","send"])});
test("SEND and RETURN share one session coordinate",async()=>{const x=rig();await x.a.send("p");await x.a.capture();assert.equal(x.s,1);assert.equal(x.r,1);assert.equal(x.ledger.get("B").state,GuardianState.RESULT_COMMITTED)});
test("separate SEND capability injection is forbidden",()=>{assert.throws(()=>rejectSeparatedCapabilityAssembly({guardian_send:()=>{}}),FinalSessionAdapterError)});
test("separate RETURN capability injection is forbidden",()=>{assert.throws(()=>rejectSeparatedCapabilityAssembly({guardian_capture:()=>{}}),FinalSessionAdapterError)});
test("coordinate drift blocks RESULT commit",async()=>{const x=rig();await x.a.send("p");x.ledger.record("B",{...x.ledger.get("B"),workId:"OTHER"});await assert.rejects(()=>x.a.capture());assert.equal(x.r,0)});
